### ISSUE TITLE
Avoid allocating a new array every time in `GetValues` and `GetNames`

### ISSUE THREAD

**Issue by Rekkonnect** [andrewlock/NetEscapades.EnumGenerators#19] opened 2022-06-09 11:53 UTC
The `GetValues` and `GetNames` allocate a new array instead of caching it; a `private static readonly` field could be used, which would be initialized either lazily or immediately.

**Comment by mandragon00** [comment] 2022-06-12 09:02
#18

**Comment by andrewlock** [comment] 2022-12-18 15:16
As discussed in #21, this is by design, so I'm going to close this for now. Thanks anyway!

**Closed by andrewlock** 2022-12-18 15:16 UTC
